webroot/adm/enclave-gcp.html, webroot/index.html
This is a static html page without any backend interaction, can be used to generate GCP EnclaveID and gcloud command line for GCP Enclave provisioning.
=> adding gcp enclave tool page

conf/logback-local.loki.xml, conf/logback.loki.xml, pom.xml, src/main/java/com/uid2/admin/audit/QLDBAuditWriter.java
In addition to logging to a QLDB, logging to Loki, a highly available logging service, makes it simple to retrieve audit logs in the future, at the cost of the lack of assurance of modification, security, etc. Adding loki auditing is not intended to replace the QLDB, indeed, the QLDB is intended to be the source of truth, and Loki logs are intended to solely be an accessible way to retrieve the same logs. If auditors need the cryptographic proof that the logs are what they should be, then they should access the QLDB instead of Loki.
=> Loki Auditing

src/main/java/com/uid2/admin/audit/QLDBAuditWriter.java, src/main/java/com/uid2/admin/audit/QLDBInit.java
This change is intended to prevent the pod from immediately crashing out if it cannot connect to the qldb due to misconfiguration
=> try-catch on qldbDriver initialization

webroot/adm/enclave-gcp.html
Rather than having to get a version of the cloud-init config that might be wrong, moved it to the page so it is harder to make mistakes with.
=> Moved cloud-init to the gcp enclave page

webroot/adm/enclave-gcp.html
Fixed bug where an empty Operator API Key (or Docker Image ID in Integration) would result in a different enclave ID. The enclave ID should remain consistent, regardless of the value of the Operator API Key
=> Ensure Enclave ID Generation does not use Operator API Key

pom.xml, src/main/java/com/uid2/admin/util/KeysetUtil.java, src/main/java/com/uid2/admin/vertx/service/EncryptionKeyService.java, src/main/java/com/uid2/admin/vertx/service/SharingService.java, src/main/resources/localstack/s3/keysets/keysets.json, src/test/java/com/uid2/admin/util/KeysetUtilTest.java, src/test/java/com/uid2/admin/vertx/EncryptionKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/SharingServiceTest.java, webroot/adm/keysets.html
1.  Change 'Add Site Ids' to 'Add Allowed Site Ids' and 'Remove Allowed Site Ids' to be less confusing
2. renamed all allowlists to allowed_sites
3.  Port Cody's changes from https://github.com/IABTechLab/uid2-admin/pull/97 to rebase off master
4. reserve right keyset id for special encryption keys
=> Syw UId2-1534 reserve right keyset id for special encryption keys

src/main/java/com/uid2/admin/vertx/RequestUtil.java
We have a hardcoded acceptable protocol lists. Add "gcp-oidc" to this list.
Verified locally:
=> allow to add new enclave-id with gcp-oidc protocol

src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/monitoring/DataStoreMetrics.java, src/main/resources/localstack/s3/partners/metadata.json
- add uid2_data_store_version metric per data store used by the admin service
- this can be used to compare the versions other (downstream) services are seeing and alert on mismatches
=> Expose data store version prometheus metrics

pom.xml, src/main/java/com/uid2/admin/secret/IKeypairManager.java, src/main/java/com/uid2/admin/store/writer/ClientSideKeypairStoreWriter.java, src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java, src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java, webroot/adm/client-side-keypairs.html
Add name field to client side keypairs.
=> initial check-in

src/test/java/com/uid2/admin/vertx/AdminKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java, src/test/java/com/uid2/admin/vertx/EncryptionKeyServiceKeysetsDisabledTest.java, src/test/java/com/uid2/admin/vertx/EncryptionKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/KeyAclServiceTest.java, src/test/java/com/uid2/admin/vertx/OperatorKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/SaltServiceTest.java, src/test/java/com/uid2/admin/vertx/SearchServiceTest.java, src/test/java/com/uid2/admin/vertx/ServiceLinkServiceTest.java, src/test/java/com/uid2/admin/vertx/ServiceServiceTest.java, src/test/java/com/uid2/admin/vertx/SharingServiceTest.java, src/test/java/com/uid2/admin/vertx/SiteServiceTest.java, src/test/java/com/uid2/admin/vertx/test/ExceptionHandler.java, src/test/java/com/uid2/admin/vertx/test/ServiceTestBase.java, src/test/java/com/uid2/admin/vertx/test/TestHandler.java
- Fixed failed test not complete until 30s timeout 
before surround with try-catch
after surround with try-catch
- Fixed multiple async asynchronous executions in a single test will not fail the test if any of the asynchronous execution is successful
=> jyg-UID2 fix vertx tests

pom.xml, src/main/java/com/uid2/admin/vertx/service/SiteService.java, src/main/resources/localstack/s3/sites/sites.json, webroot/adm/site.html
- New api endpoint `/api/site/update` which currently handles `description` and `visible`
- Allow `description` to be passed to add site method
- Add buttons to the UI to set description and visible 
- The first commit is purely formatting changes
- Relevant changes in shared: https://github.com/IABTechLab/uid2-shared/pull/157
**Listing sites**
https://github.com/IABTechLab/uid2-admin/assets/137864392/b1e90df9-2c10-448f-9e71-b18cad30b907
**Adding a new site with a description**
https://github.com/IABTechLab/uid2-admin/assets/137864392/091db096-4251-452c-aa4f-8ae05b5ab986
**Adding a site with no description**
https://github.com/IABTechLab/uid2-admin/assets/137864392/7814cc9c-c99f-4147-9b94-4cabb04a4f74
**Updating a site**
https://github.com/IABTechLab/uid2-admin/assets/137864392/90d5f466-18 …
=> Allow updating new site fields in UI

src/main/java/com/uid2/admin/vertx/service/SharingService.java, src/test/java/com/uid2/admin/vertx/SharingServiceTest.java
`!existingAllowedSites.contains(s)` was causing an NPE when `existingAllowedSites` was `null`. This PR fixes that issue and adds a test for this situation.
**Manual tests in the Portal**
No longer receives a 500 from admin and crashes when `allowed_sites` is `null` - it now works as you would expect.
https://github.com/IABTechLab/uid2-admin/assets/137864392/4d0aed60-1d33-4b5c-8998-bc0155dc7a35
**Manual tests in Admin UI**
Preserves functionality.
https://github.com/IABTechLab/uid2-admin/assets/137864392/8d25e09e-5223-440e-a2c0-da710041640f
=> Prevent NPE when updating allowed_sites from null

src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java, src/main/resources/localstack/s3/admins/admins.json, src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java
- Allow users with `Role.SHARING_PORTAL` to call `/api/client_side_keypairs/add`
- Add a local admin key that only has `SHARING_PORTAL` to be used for devs. The associated changed in the portal is in https://github.com/IABTechLab/uid2-self-serve-portal/pull/227
=> Ensure roles are consistent for portal

src/main/resources/localstack/s3/core/clients/clients.json
In the portal, we filter out sites that do not have the associated roles of `SHARER` or `ID_READER`, unless they are a DSP. This change adds these roles so that we have at least one example of an advertiser and publisher with the default dev setup.
=> Fix clients json data for portal

src/main/java/com/uid2/admin/legacy/LegacyClientKey.java, src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java, src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java, webroot/adm/client-key.html
Separating contact and name fields of clients keys. This way contact can be used for logging and is uniquely identifiably for TTD tracking while the name can be anything, allowing users to give keys names relevant to them. Names do not have to unique anymore. Contact will still be unique and is generated based on a combination of the site name and the keyId.
Changed layout of page for more logical flow, now each operation will have popups for the different information they need apart from contact.
Changing the contact of a key will require the new contact to be filled in in a new popup along with a second confirmation.
=> Separating Contact and Name field for client keys

pom.xml, src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/monitoring/DataStoreMetrics.java, src/main/resources/localstack/s3/core/services/services.json
We'll be using uid2-admin to host the metrics for the snowflake account metadata and number of snowflake accounts. I've added a new data store method to retrieve the number of snowflake service links, and added a new data store for service link version.
I've also added the ID_READER and GENERATOR roles to the local snowflake service to reflect the roles required for the snowflake accounts.
=> sch-UID2-2516-redirect-snowflake-etl-to-read-from-service-links-implementation

webroot/adm/client-key.html, webroot/adm/search.html, webroot/adm/site.html
Some inputs were not encoded, so if they contained special characters (e.g. `+`, `&`) they would not be properly sent in the request and hence would return a 404.
Also included some minor formatting + syntax changes.
**Before**
Note the `+` is cut off from the payload.
**After**
Note the `+` is properly encoded as `%2B`
=> Support special characters in search

webroot/adm/search.html
The input for the "Secret" search actually breaks when it is encoded, so reverting a change I made in https://github.com/IABTechLab/uid2-admin/pull/224
=> Remove encoding from secret search input

.trivyignore, Dockerfile, pom.xml
- Update eclipse-temurin version
- This addresses `CVE-2024-28757` and `CVE-2023-52425`
- Successful run: https://github.com/IABTechLab/uid2-admin/actions/runs/8352156839/job/22861786259:
```
ghcr.io/iabtechlab/uid2-admin:5.2.5-SNAPSHOT-default (alpine 3.19.1)
====================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```
=> Address CVE-2024-28757 and CVE-2023-52425 vulnerabilities

src/main/java/com/uid2/admin/vertx/service/KeyAclService.java, src/test/java/com/uid2/admin/vertx/KeyAclServiceTest.java, webroot/adm/key-acl.html, webroot/index.html
1. Disable setting Key ACL and make it read only within the admin service GUI
2. Mark Key ACL overall deprecated and separate away from normal admin functionalities
3. Disabled Key ACL reset/update endpoints and related unit tests
See the below admin service page for the actual GUI changes.
=> Disable writing Key ACLs

pom.xml, src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/managers/S3KeyManager.java, src/main/java/com/uid2/admin/vertx/service/OperatorKeyService.java, src/test/java/com/uid2/admin/managers/S3KeyManagerTest.java, src/test/java/com/uid2/admin/vertx/OperatorKeyServiceTest.java
also enhanced code readability in the S3 keys manager
=> Create s3 keys for newly added operators

webroot/adm/oncall/generate-api-key-secret.html
Current role labels are misleading
=> Fix Role Labels in oncall key creation page

src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/store/parser/AdminKeysetParser.java, src/main/java/com/uid2/admin/vertx/service/SharingService.java, src/main/resources/localstack/s3/core/keysets/keysets.json, src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java, src/test/java/com/uid2/admin/vertx/SharingServiceTest.java, webroot/adm/oncall/participant-summary.html, webroot/js/participantSummary.js
UI looks below. It will highlight the reason why the keyset is related to the participant. Also tested the rotation works.
=> UID2-3506 Add functionality on oncall page to list related keysets and rotate them

pom.xml, src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/vertx/Endpoints.java
Meter filter logic for path normalisation has been moved to Shared to be used across all apps.
=> sch-UID2-4073 high level tests for path normalisation in metrics

Dockerfile
This unused arg causes the entire build context to be copied to /app/conf, including 1.7G of Trivy cache files.
=> Remove EXTRA_CONFIG build arg

.gitignore, src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/managers/CloudEncryptionKeyManager.java, src/test/java/com/uid2/admin/managers/CloudEncryptionKeyManagerTest.java
Bassic refactorings of CloudEncryptionKeyManager, should not have any changes in behavior:
1. Removed `public` from methods that aren't actually public
2. Moved the only actual public method to the top
3. Rearranged the logic to be a bit less nested, extracted a few helpers
4. Broken up really long lines that don't fit on my laptop monitor
5. Reduced repetition of common test data in the test
=> Basic preliminary refactoring to make sense of stuff

src/main/java/com/uid2/admin/store/writer/EncryptedSaltStoreWriter.java, src/main/java/com/uid2/admin/store/writer/SaltSerializer.java, src/main/java/com/uid2/admin/store/writer/SaltStoreWriter.java, src/test/java/com/uid2/admin/store/writer/EncryptedSaltStoreWriterTest.java, src/test/java/com/uid2/admin/store/writer/SaltSerializerTest.java
From the next salt rotation the new fields will be added empty to the salt file. (Test data above, not real salts)
Operator loads the salts with no code changes.
=> Serializing new salt fields

conf/default-config.json, conf/local-config.json, src/main/java/com/uid2/admin/AdminConst.java, src/main/java/com/uid2/admin/Main.java, src/main/java/com/uid2/admin/secret/SaltRotation.java, src/test/java/com/uid2/admin/secret/SaltRotationTest.java
Salts will only be considered for rotation if their refresh_from is equal to the target date. Feature is behind a feature switch, which can be enabled through the admin config file.
Unit test:
* salts that are old enough to rotate and are refreshing on target date will be considered for rotation
* salts that not old enough to rotate and are refreshing on the target date are not rotated
* salts that are old enough to rotate but are not refreshing on target date are not rotated
* refresh_from dates are updated appropriately
=> sch-UID2-5352 honouring refresh from in salt rotation

src/main/java/com/uid2/admin/cloudencryption/CloudEncryptionKeyManager.java
No throw when backfillKeys() fails
=> No throw when backfillKeys() fails

src/main/java/com/uid2/admin/vertx/Endpoints.java, src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java, src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java, webroot/adm/client-side-keypair.html
UI and output look like:
Asks for confirmation:
[
](url)
=> Add the ability to delete client-side keypairs

webroot/adm/oncall/participant-summary.html, webroot/js/component/participantSummary.js
What I Added:
- API Key Usage
- CSTG Dashboard
- Operator Dashboard (if participant has operator keys)
- Optout Dashboard (if participant has opt out webhooks)
- API Calls by Key for each API key a participant has
- Conditionally determining URL based on UID2 or EUID, prod or integ or test, and the site id or contact
=> additional admin participant summary work adding grafana links
