IABTechLab/uid2-admin

- src/main/java/com/uid2/admin/secret/IKeyGenerator.java
- src/main/java/com/uid2/admin/secret/SecureKeyGenerator.java
- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/test/java/com/uid2/admin/vertx/test/ServiceTestBase.java
* Make generateRandomKeyString mockable
> * Client secret should be base64 encoded.

- conf/default-config.json
- conf/local-config.json
- pom.xml
- src/main/java/com/uid2/admin/Constants.java
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/audit/AuditFactory.java
- src/main/java/com/uid2/admin/audit/AuditHandler.java
- src/main/java/com/uid2/admin/audit/AuditMiddleware.java
- src/main/java/com/uid2/admin/audit/AuditMiddlewareImpl.java
- src/main/java/com/uid2/admin/audit/AuditWriter.java
- src/main/java/com/uid2/admin/audit/QLDBAuditMiddleware.java
- src/main/java/com/uid2/admin/audit/QLDBAuditModel.java
- src/main/java/com/uid2/admin/audit/QLDBAuditWriter.java
- src/main/java/com/uid2/admin/audit/Type.java
- src/main/java/com/uid2/admin/vertx/service/AdminKeyService.java
Resubmitted PR.
Added implementations of various interfaces, and added logging capabilities to AdminKeyService.java. Logging is disabled in this PR (governed by a constant in the config files), and currently enabling logging will not log anything to the QLDB due to lack of credentials. Tests will be included in a later PR.
> Admin Logging Implementation for AdminKeyService (new PR)

- conf/default-config.json
- conf/local-config.json
turn on qldb logging
can't believe I forgot this
> turn on qldb logging

- conf/local-config.json
- src/main/java/com/uid2/admin/Constants.java
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/audit/Actions.java
- src/main/java/com/uid2/admin/audit/AdminQLDBInit.java
- src/main/java/com/uid2/admin/audit/AuditFactory.java
- src/main/java/com/uid2/admin/audit/AuditMiddleware.java
- src/main/java/com/uid2/admin/audit/AuditMiddlewareImpl.java
- src/main/java/com/uid2/admin/audit/AuditWriter.java
- src/main/java/com/uid2/admin/audit/IAuditInit.java
- src/main/java/com/uid2/admin/audit/IAuditMiddleware.java
- src/main/java/com/uid2/admin/audit/IAuditModel.java
- src/main/java/com/uid2/admin/audit/IAuditWriter.java
- src/main/java/com/uid2/admin/audit/QLDBAuditModel.java
- src/main/java/com/uid2/admin/audit/QLDBAuditWriter.java
- src/main/java/com/uid2/admin/audit/QLDBInit.java
- src/main/java/com/uid2/admin/vertx/service/AdminKeyService.java
- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/main/java/com/uid2/admin/vertx/service/EnclaveIdService.java
- src/main/java/com/uid2/admin/vertx/service/EncryptionKeyService.java
- src/main/java/com/uid2/admin/vertx/service/KeyAclService.java
- src/main/java/com/uid2/admin/vertx/service/OperatorKeyService.java
- src/main/java/com/uid2/admin/vertx/service/PartnerConfigService.java
- src/main/java/com/uid2/admin/vertx/service/SaltService.java
- src/main/java/com/uid2/admin/vertx/service/SiteService.java
- src/test/java/com/uid2/admin/vertx/AdminLogTest.java
- src/test/java/com/uid2/admin/vertx/SaltServiceTest.java
- src/test/java/com/uid2/admin/vertx/test/ServiceTestBase.java
Would like to attempt integ with failure resistance changes. If it breaks everything I'll revert in k8
> Latest Admin version

- pom.xml
- src/main/java/com/uid2/admin/vertx/service/OperatorKeyService.java
- src/main/resources/localstack/s3/operators/operators.json
- src/test/java/com/uid2/admin/vertx/OperatorKeyServiceTest.java
- webroot/adm/operator-key.html
Create new operator key functionalities to update OperatorKey.publicOperator field:
> Uid2-598 differentiate public private operator

- pom.xml
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/job/JobDispatcher.java
- src/main/java/com/uid2/admin/job/jobsync/PrivateSiteDataSyncJob.java
- src/main/java/com/uid2/admin/job/jobsync/acl/KeyAclSyncJob.java
- src/main/java/com/uid2/admin/job/jobsync/client/ClientKeySyncJob.java
- src/main/java/com/uid2/admin/job/jobsync/key/EncryptionKeySyncJob.java
- src/main/java/com/uid2/admin/job/jobsync/site/SiteSyncJob.java
- src/main/java/com/uid2/admin/job/model/Job.java
- src/main/java/com/uid2/admin/job/model/JobInfo.java
- src/main/java/com/uid2/admin/store/InstantClock.java
- src/main/java/com/uid2/admin/vertx/AdminVerticle.java
- src/main/java/com/uid2/admin/vertx/JsonUtil.java
- src/main/java/com/uid2/admin/vertx/service/JobDispatcherService.java
- src/main/java/com/uid2/admin/vertx/service/PrivateSiteDataRefreshService.java
- src/test/java/com/uid2/admin/job/JobDispatcherTest.java
- src/test/java/com/uid2/admin/job/jobsync/client/ClientKeySyncJobTest.java
Testing:
- Added unit tests
- While a job was executing, checked http://localhost:9089/metrics and saw the job execution duration in the output
> Added execution duration metric and stats API for job dispatcher

- pom.xml
> Updated patch number

- pom.xml
Creating a new version to test the deployment pipeline. No code change from 2.0.0
> Only to test a new deployment

- pom.xml
- webroot/adm/enclave-gcp.html
> advtoken lifetime in gcp private operators should be 1 day

- src/main/java/com/uid2/admin/vertx/service/SharingService.java
- src/test/java/com/uid2/admin/vertx/SharingServiceTest.java
- webroot/adm/keysets.html
Handle potential keyset request cases as defined here:
https://atlassian.thetradedesk.com/confluence/display/UID2/UID2-545+Sharing+-+Data+Storage+for+Keys+and+Grants#UID2545SharingDataStorageforKeysandGrants-Risks
> Ian UI d2 1533 admin sharing error test coverage

- src/main/java/com/uid2/admin/vertx/ResponseUtil.java
- src/main/java/com/uid2/admin/vertx/service/SharingService.java
- src/test/java/com/uid2/admin/vertx/SharingServiceTest.java
- webroot/adm/encryption-key.html
- webroot/adm/keysets.html
- webroot/js/main.js
PULL REQUEST MOVED HERE as branch name was incorrect
https://github.com/IABTechLab/uid2-admin/pull/107
> Ian Moved here https://github.com/IABTechLab/uid2-admin/pull/107

- webroot/adm/enclave-gcp-v2.html
- webroot/index.html
Add a new page for GCP enclave v2 (OIDC).
- Mimiced existing GCP enclave page.
Screenshot:
> add gcp enclave page V2.

- webroot/adm/encryption-key.html
- webroot/adm/keysets.html
[UID2-1598](https://atlassian.thetradedesk.com/jira/browse/UID2-1598)
> UID2-1598 Improve Keysets and Encryption Keys UI

- src/main/java/com/uid2/admin/vertx/service/SharingService.java
> bugfix missing return statement

- src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java
- trivy-secret.yaml
[UID2-1703](https://atlassian.thetradedesk.com/jira/browse/UID2-1703)
> add cstg key to trivy-secret.yaml

- README.md
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/secret/IKeypairManager.java
- src/main/java/com/uid2/admin/vertx/AdminVerticle.java
- src/main/java/com/uid2/admin/vertx/api/IBlockingRouteProvider.java
- src/main/java/com/uid2/admin/vertx/api/IRouteProvider.java
- src/main/java/com/uid2/admin/vertx/api/UrlParameterProviders.java
- src/main/java/com/uid2/admin/vertx/api/V2Router.java
- src/main/java/com/uid2/admin/vertx/api/V2RouterModule.java
- src/main/java/com/uid2/admin/vertx/api/annotations/ApiMethod.java
- src/main/java/com/uid2/admin/vertx/api/annotations/Method.java
- src/main/java/com/uid2/admin/vertx/api/annotations/Path.java
- src/main/java/com/uid2/admin/vertx/api/annotations/Roles.java
- src/main/java/com/uid2/admin/vertx/api/cstg/ClientSideKeypairResponse.java
- src/main/java/com/uid2/admin/vertx/api/cstg/GetClientSideKeypairsBySite.java
- src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java
- src/test/java/com/uid2/admin/v2Router/RouterConfigurationTest.java
- src/test/java/com/uid2/admin/v2Router/SiteId_ClientSideKeypair_Test.java
- src/test/java/com/uid2/admin/vertx/test/ServiceTestBase.java
Introduce attribute-based routing configuration.
Add a router to handle a site-specific request for client-side keypairs.
> Add a new v2 router section.

- README.md
- webroot/adm/administrators.html
- webroot/adm/client-key.html
- webroot/adm/client-side-keypairs.html
- webroot/adm/operator-key.html
- Used roughly existing pattern for confirmations and validation when submitting an action, mainly around disabling or enabling keys.
- Extracted validation where it made sense - though more effort needs to be done here across all the pages
- Added README section to help devs work on the UI
**Disabling and enabling a client key**
https://github.com/IABTechLab/uid2-admin/assets/137864392/f8268cc3-11cf-450e-8460-7cdc98dcbbcf
**Basic validation**
https://github.com/IABTechLab/uid2-admin/assets/137864392/86325fa8-7f65-4a58-8000-382ec809c9b0
> Confirmations and basic validation when editing keys in UI

- pom.xml
- src/main/java/com/uid2/admin/auth/AdminUser.java
- src/main/java/com/uid2/admin/legacy/LegacyClientKey.java
- src/main/java/com/uid2/admin/vertx/service/AdminKeyService.java
- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/main/java/com/uid2/admin/vertx/service/OperatorKeyService.java
- src/test/java/com/uid2/admin/auth/AdminUserProviderTest.java
- src/test/java/com/uid2/admin/job/jobsync/client/ClientKeySyncJobTest.java
- src/test/java/com/uid2/admin/job/sitesync/SiteSyncJobTest.java
- src/test/java/com/uid2/admin/managers/KeysetManagerTest.java
- src/test/java/com/uid2/admin/store/writer/ClientKeyStoreTest.java
- src/test/java/com/uid2/admin/util/PrivateSiteUtilTest.java
- src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java
- src/test/java/com/uid2/admin/vertx/OperatorKeyServiceTest.java
- src/test/java/com/uid2/admin/vertx/SearchServiceTest.java
- src/test/java/com/uid2/admin/vertx/SiteServiceTest.java
- src/test/java/com/uid2/admin/vertx/test/ServiceTestBase.java
> UID2-2054 Create keyid field

- src/main/java/com/uid2/admin/vertx/RequestUtil.java
- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/main/java/com/uid2/admin/vertx/service/KeyAclService.java
- src/main/java/com/uid2/admin/vertx/service/OperatorKeyService.java
- src/main/java/com/uid2/admin/vertx/service/SiteService.java
- src/test/java/com/uid2/admin/vertx/SiteServiceTest.java
- webroot/adm/site.html
Added api call "/api/site/:siteId"
> Add get site by id endpoint

- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java
- webroot/adm/client-key.html
Added endpoint to return all keys based on a siteId.
Also added search to call this endpoint on panel.
> Added end point to get keys by site id

- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java
- webroot/adm/client-key.html
Added a new endpoint to allow to search for client key by siteId. Added button to ui.
Also allowed portal to use edit endpoints to allow it to edit apiKeys.
> Allow search by keyId and allow portal to use edit endpoints

- src/main/java/com/uid2/admin/vertx/service/ClientKeyService.java
- src/test/java/com/uid2/admin/vertx/ClientKeyServiceTest.java
- webroot/adm/client-key.html
Added search by contact button to client key page
> Client Key Search by contact

- src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java
- src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java
> Add site_name for keypairs

- src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java
- src/test/java/com/uid2/admin/vertx/ClientSideKeypairServiceTest.java
> Hide CSTG private key at time of creation

- .github/workflows/validate-image.yaml
Successful run: https://github.com/IABTechLab/uid2-admin/actions/runs/8045648500
> UID2-2864 Raise failure_severity to CRITICAL

- conf/local-config.json
- src/main/java/com/uid2/admin/vertx/service/ClientSideKeypairService.java
allow portal to update keypairs
enforce authorization in local dev mode
> allow portal to update keypairs

- pom.xml
- src/main/java/com/uid2/admin/vertx/service/SiteService.java
- src/test/java/com/uid2/admin/vertx/SiteServiceTest.java
- webroot/adm/site.html
> Adding the ability to rename sites

- README.md
- conf/local-config.json
> Disable local auth by default

- webroot/index.html
> Moved deprecated header to the actual item otherwise Deprecated header will appear in login screen

- webroot/adm/oncall/generate-cstg-keypair.html
**Before**
https://github.com/IABTechLab/uid2-admin/assets/137864392/6900d747-fcb1-471f-88ce-04bb15c76442
**After**
https://github.com/IABTechLab/uid2-admin/assets/137864392/866a2881-2e2f-4325-9569-1698184faf93
> Remove encoding for keypair name for oncall flow

- conf/local-config.json
- pom.xml
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/managers/S3KeyManager.java
- src/main/java/com/uid2/admin/store/writer/S3KeyStoreWriter.java
- src/main/java/com/uid2/admin/vertx/service/OperatorKeyService.java
- src/test/java/com/uid2/admin/managers/S3KeyManagerTest.java
- src/test/java/com/uid2/admin/store/writer/S3KeyStoreWriterTest.java
S3 key manager handles logics of generating S3 keys 
verified both s3encyrption_keys and metadata file can be successfully written to local stack
> added s3 keys generator

- conf/local-config.json
- conf/local-e2e-docker-config.json
- pom.xml
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/managers/S3KeyManager.java
- src/main/java/com/uid2/admin/store/writer/S3KeyStoreWriter.java
- src/test/java/com/uid2/admin/managers/S3KeyManagerTest.java
- src/test/java/com/uid2/admin/store/writer/S3KeyStoreWriterTest.java
previously https://github.com/IABTechLab/uid2-admin/pull/290
> all the old changes for S3 keys generator added back to a new branch

- pom.xml
- src/main/java/com/uid2/admin/Main.java
- src/main/java/com/uid2/admin/vertx/service/EnclaveIdService.java
- src/test/java/com/uid2/admin/vertx/EnclaveIdServiceTest.java
- src/test/java/com/uid2/admin/vertx/test/ServiceTestBase.java
Added validations for the admin Enclave Id endpoints.
Check for duplicate enclave Id and protocol.
Added unit tests for all the end points
> Check duplicate enclave

- webroot/adm/oncall/participant-summary.html
- webroot/adm/oncall/search.html
- webroot/css/participantSummary.css
- webroot/index.html
- webroot/js/main.js
- webroot/js/participantSummary.js
Add new on call tab for Participant Summary
> Participant Summary Tab

- webroot/adm/oncall/participant-summary.html
- webroot/css/participantSummary.css
- webroot/js/participantSummary.js
https://github.com/user-attachments/assets/9bc5a889-f7a5-4c74-abee-c7e9b5a53299
> auto-complete for site in participant summary

- src/main/java/com/uid2/admin/vertx/RequestUtil.java
- src/main/resources/localstack/s3/core/operators/operators.json
- src/test/java/com/uid2/admin/vertx/EnclaveIdServiceTest.java
This reverts commit 484a5a0b9db6d0238f07482a8a0ec7e6edd2fa38.
> Revert "Add `azure-cc-aks` to allowed protocols (#368)"

- pom.xml
- src/test/java/com/uid2/admin/store/writer/EncryptedSaltStoreWriterTest.java
`decryptInputStream` needs to be updated after upgrading `uid2-shared`
> Fixed tests with decryptInputStream
